### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by michaeljdennis** [thechangelog/beyondcode#9]
The SSL/TLS certificate for https://beyondcode.tv has expired.

**Comment by jerodsanto** [comment]
Thanks for the report @michaeljdennis! Between our whois privacy, cert provider (DNSimple), and host (AWS), I'm having hard time getting this renewed easily.

Working on it, though!

**Comment by jerodsanto** [comment]
Fixed! Never did get the DNSimple cert working, but Let's Encrypt came to the rescue!

Thanks again for hollering at us 💚

**Comment by michaeljdennis** [comment]
Yes, Let's Encrypt is great! Glad to help. Keep up the great work @thechangelog!
